## Try and Except:
The `try` block lets you test a block of code for errors.
The `except` block lets you handle the error.
The `finally` block lets you execute code, regardless of the result of the try/except blocks.

#### Syntax:
```py
try:
	print(x)
except:
	print("An exception occurred")
	
# The `try` block will generate an exception, because x is not defined
```



[Python Try Except](https://www.w3schools.com/python/python_try_except.asp)



We can use `try` statements to handle exceptions. There are four clauses you can use (one more in addition to those shown in the video).

-   `try`: This is the only mandatory clause in a `try` statement. The code in this block is the first thing that Python runs in a `try` statement.
-   `except`: If Python runs into an exception while running the `try` block, it will jump to the `except` block that handles that exception.
-   `else`: If Python runs into no exceptions while running the `try` block, it will run the code in this block after running the `try` block.
-   `finally`: Before Python leaves this `try` statement, it will run the code in this `finally` block under any conditions, even if it's ending the program. E.g., if Python ran into an error while running code in the `except` or `else` block, this `finally` block will still be executed before stopping the program.


# Accessing Error Messages

When you handle an exception, you can still access its error message like this:

```
try:
    # some code
except ZeroDivisionError as e:
   # some code
   print("ZeroDivisionError occurred: {}".format(e))
```

This would print something like this:

```
ZeroDivisionError occurred: integer division or modulo by zero
```

So you can still access error messages, even if you handle them to keep your program from crashing!

If you don't have a specific error you're handling, you can still access the message like this:

```
try:
    # some code
except Exception as e:
   # some code
   print("Exception occurred: {}".format(e))
```

`Exception` is just the base class for all built-in exceptions. You can learn more about Python's exceptions [here](https://docs.python.org/3/library/exceptions.html#bltin-exceptions).